name: Deploy Web Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Create docker image for server
        run: docker build -t dilakshanchandrasena/petbay-server ./Server
      - name: Push Server docker image to dockerhub
        run: docker push dilakshanchandrasena/petbay-server:latest
      - name: Create docker image for client
        run: docker build -t dilakshanchandrasena/petbay-client --build-arg VITE_SERVER_NODE_ENV='production' --build-arg VITE_PROD_BASE_URL='${{ secrets.VITE_PROD_BASE_URL }}'  ./Client
      - name: Push Server docker image to dockerhub
        run: docker push dilakshanchandrasena/petbay-client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Server image from docker hub
        run: docker pull dilakshanchandrasena/petbay-server:latest
      - name: Pull Client from docker hub
        run: docker pull dilakshanchandrasena/petbay-client:latest
      - name: Delete old container
        run: docker rm -f petbay-server-container
      - name: Delete old container
        run: docker rm -f petbay-client-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name petbay-server-container dilakshanchandrasena/petbay-server
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name petbay-client-container dilakshanchandrasena/petbay-client
